Hot seat
Leonidas51/prompt-game pull request #1
Opened 2023-01-30 21:34 UTC by Pauline-sh

![image](https://user-images.githubusercontent.com/35494252/215600066-57ddefbb-0264-416f-9741-2913fbbe5b1d.png)

2023-01-31 16:27 UTC, Leonidas51 requested changes

2023-01-31 16:27 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +const GuessStatusRecord = Object.freeze({
мб `const GuessStatusRecord = { ... } as const` ?

2023-01-31 16:27 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +  // eslint-disable-next-line no-plusplus
Давай выпилим нах это правило из конфига

2023-01-31 16:27 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +function getNextPlayer(items: number[], currentItem: number): number {
function?

2023-01-31 16:27 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +  }, [currentPlayer, score]);
посмотри в нетворке, useEffect каждый раз вызывается и создает новое сокет-соединение

2023-01-31 16:27 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +          <span className={`word-status ${guessStatus === 'FOUND' ? 'found' : ''}`}>
у нас тут типо бэм... я бы выпилил в верстке айдишники и везде поставил вызов `className()`, как выше. found здесь буит тип модификатор. И добавить вложенность в стили, у нас есть для этого плагин https://github.com/postcss/postcss-nested

2023-01-31 16:31 UTC, Leonidas51 commented
Вообще кул функциональчик. И может (раз это лишь одна из вариаций игры) стоит уже сейчас подумать как на фронте разделить общую логику игры и логику специфичную для хотсита

2023-01-31 17:07 UTC, Leonidas51 commented on client/src/containers/game/index.tsx
> +        {players.map((player) => (
нада key

2023-01-31 20:34 UTC, Pauline-sh commented on client/src/containers/game/index.tsx
> +function getNextPlayer(items: number[], currentItem: number): number {
тока конст используем?

2023-01-31 20:40 UTC, Pauline-sh commented on client/src/containers/game/index.tsx
> +  }, [currentPlayer, score]);
вот это багос, спасибо

2023-01-31 20:53 UTC, Pauline-sh commented on client/src/containers/game/index.tsx
> +        {players.map((player) => (
((

2023-01-31 20:54 UTC, Pauline-sh commented
> Вообще кул функциональчик. И может (раз это лишь одна из вариаций игры) стоит уже сейчас подумать как на фронте разделить общую логику игры и логику специфичную для хотсита

ты прав, надо поделить, но пока не хотела усложнять, так как есть желание поскорее прикрутить олнлайн мультиплеер

2023-02-23 15:43 UTC, Leonidas51 approved these changes

2023-02-23 15:43 UTC, Leonidas51 commented
гуд щит 👍

2023-02-23 15:44 UTC, merged